name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Get version from project
        id: version
        run: |
          # Find the .csproj file
          $csprojFile = Get-ChildItem -Path . -Filter "*.csproj" -Recurse | Select-Object -First 1
          if (-not $csprojFile) {
            Write-Error "Could not find any .csproj file"
            exit 1
          }
          
          Write-Host "Found .csproj file: $($csprojFile.FullName)"
          
          # Store the project path for later use
          $relativePath = $csprojFile.FullName.Replace((Get-Location).Path + "\", "").Replace("\", "/")
          echo "PROJECT_PATH=$relativePath" >> $env:GITHUB_OUTPUT
          
          # Read and parse the XML
          [xml]$projectXml = Get-Content $csprojFile.FullName
          $versionNode = $projectXml.SelectSingleNode("//Version")
          
          if (-not $versionNode -or [string]::IsNullOrEmpty($versionNode.InnerText)) {
            Write-Error "Could not find <Version> element in $($csprojFile.Name)"
            Write-Host "Project file content:"
            Get-Content $csprojFile.FullName | Write-Host
            exit 1
          }
          
          $version = $versionNode.InnerText.Trim()
          Write-Host "Found version: $version"
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        shell: powershell

      - name: Check if release exists
        id: check_release
        run: |
          $version = "${{ steps.version.outputs.VERSION }}"
          $tag = "v$version"
          $releaseExists = $false
          Write-Host "Checking if release $tag already exists..."
          
          # Use GitHub API directly
          $headers = @{
            'Authorization' = "token $env:GITHUB_TOKEN"
            'Accept' = 'application/vnd.github.v3+json'
          }
          
          try {
            $response = Invoke-RestMethod -Uri "https://api.github.com/repos/$env:GITHUB_REPOSITORY/releases/tags/$tag" -Headers $headers -Method Get
            if ($response) {
              $releaseExists = $true
              Write-Host "Release $tag already exists, skipping build steps..."
            }
          } catch {
            if ($_.Exception.Response.StatusCode -eq 404) {
              Write-Host "Release $tag does not exist, proceeding with build..."
            } else {
              Write-Host "Error checking release: $($_.Exception.Message)"
              Write-Host "Proceeding with build anyway..."
            }
          }
          
          echo "RELEASE_EXISTS=$($releaseExists.ToString().ToLower())" >> $env:GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
        shell: powershell

      - name: Clean for fresh build
        if: steps.check_release.outputs.RELEASE_EXISTS == 'false'
        run: dotnet clean "${{ steps.version.outputs.PROJECT_PATH }}" --configuration Release

      - name: Restore dependencies
        if: steps.check_release.outputs.RELEASE_EXISTS == 'false'
        run: dotnet restore "${{ steps.version.outputs.PROJECT_PATH }}"

      - name: Build Release
        if: steps.check_release.outputs.RELEASE_EXISTS == 'false'
        run: dotnet build "${{ steps.version.outputs.PROJECT_PATH }}" --configuration Release --no-restore

      - name: Publish Windows x64 (Self-Contained)
        if: steps.check_release.outputs.RELEASE_EXISTS == 'false'
        run: dotnet publish "${{ steps.version.outputs.PROJECT_PATH }}" --configuration Release --runtime win-x64 --self-contained true --output ./publish/win-x64-selfcontained

      - name: Publish Windows x86 (Self-Contained)
        if: steps.check_release.outputs.RELEASE_EXISTS == 'false'
        run: dotnet publish "${{ steps.version.outputs.PROJECT_PATH }}" --configuration Release --runtime win-x86 --self-contained true --output ./publish/win-x86-selfcontained

      - name: Publish Windows x64 (Framework-Dependent)
        if: steps.check_release.outputs.RELEASE_EXISTS == 'false'
        run: dotnet publish "${{ steps.version.outputs.PROJECT_PATH }}" --configuration Release --runtime win-x64 --self-contained false --output ./publish/win-x64-framework

      - name: Publish Windows x86 (Framework-Dependent)
        if: steps.check_release.outputs.RELEASE_EXISTS == 'false'
        run: dotnet publish "${{ steps.version.outputs.PROJECT_PATH }}" --configuration Release --runtime win-x86 --self-contained false --output ./publish/win-x86-framework

      - name: Create ZIP packages
        if: steps.check_release.outputs.RELEASE_EXISTS == 'false'
        run: |
          # Self-contained versions
          Compress-Archive -Path ./publish/win-x64-selfcontained/* -DestinationPath ./RemuxOpt-win-x64-selfcontained.zip -Force
          Compress-Archive -Path ./publish/win-x86-selfcontained/* -DestinationPath ./RemuxOpt-win-x86-selfcontained.zip -Force
          
          # Framework-dependent versions
          Compress-Archive -Path ./publish/win-x64-framework/* -DestinationPath ./RemuxOpt-win-x64-framework.zip -Force
          Compress-Archive -Path ./publish/win-x86-framework/* -DestinationPath ./RemuxOpt-win-x86-framework.zip -Force
          
          Write-Host "Created ZIP packages:"
          Get-Item ./RemuxOpt-win-*.zip | ForEach-Object {
            Write-Host "$($_.Name): $([math]::Round($_.Length / 1MB, 2)) MB"
          }
        shell: powershell

      - name: Create Release
        if: steps.check_release.outputs.RELEASE_EXISTS == 'false'
        run: |
          $version = "${{ steps.version.outputs.VERSION }}"
          $tag = "v$version"
          $title = "RemuxOpt v$version"
          
          # Create release notes
          $releaseNotes = @"
          ## RemuxOpt v$version
          Auto-generated release from GitHub Actions build.
          
          ## Download Options
          
          ### 🚀 Self-Contained (Recommended for most users)
          **No .NET installation required** - Everything included
          - **Windows 64-bit**: RemuxOpt-win-x64-selfcontained.zip (~100-200MB)
          - **Windows 32-bit**: RemuxOpt-win-x86-selfcontained.zip (~100-200MB)
          
          ### 📦 Framework-Dependent (Smaller download)
          **Requires .NET 8.0 Runtime** - Download from: https://dotnet.microsoft.com/download/dotnet/8.0
          - **Windows 64-bit**: RemuxOpt-win-x64-framework.zip (~10-50MB)
          - **Windows 32-bit**: RemuxOpt-win-x86-framework.zip (~10-50MB)
          
          ### Which should I choose?
          - **Self-Contained**: Just download, extract, and run - no additional setup needed
          - **Framework-Dependent**: Smaller download, but you need to install .NET 8.0 Runtime first
          "@
          
          # Save release notes to file
          $releaseNotes | Out-File -FilePath "release-notes.md" -Encoding UTF8
          
          Write-Host "Creating release $tag with title: $title"
          Write-Host "Files to upload:"
          Get-Item ./RemuxOpt-win-*.zip | ForEach-Object {
            Write-Host "  $($_.Name)"
          }
          
          # Create release using GitHub CLI
          gh release create "$tag" `
            --title "$title" `
            --notes-file "release-notes.md" `
            ./RemuxOpt-win-x64-selfcontained.zip `
            ./RemuxOpt-win-x86-selfcontained.zip `
            ./RemuxOpt-win-x64-framework.zip `
            ./RemuxOpt-win-x86-framework.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: powershell
